name: Build
on:
  push:
    branches:
      - main
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc
    - name: Install
      uses: pnpm/action-setup@v2.2.1
      with:
        version: 8
        run_install: true
    - name: Lint
      run: pnpm run lint
    - name: Test
      run: pnpm run test -- --coverage
    - name: Report
      uses: coverallsapp/github-action@v1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./artifacts/coverage/lcov.info
    - name: Build
      run: pnpm run build
    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: pnpm run release
